const bands = [
 {
  name: "AC/DC",
  origin: "Sydney, Australia",
  genre: "Rock, Heavey metal",
  formedYear: 1973,
  cost: 650000,
  img: "https://i.ibb.co/ftfbfYn/ACDC.jpg",
 },
 {
  name: "Iron Maiden",
  origin: "London, United Kingdom",
  genre: "Heavey metal",
  formedYear: 1975,
  cost: 710000,
  img: "https://i.ibb.co/KVY34Yg/iron-maiden.jpg",
 },
 {
  name: "Megadeth",
  origin: "California, US",
  genre: "Thrash metal, Heavey metal",
  formedYear: 1983,
  cost: 850000,
  img: "https://i.ibb.co/b3pK1CD/megadeth.jpg",
 },
 {
  name: "Deep Purple",
  origin: "London, United Kingdom",
  genre: "Heavy metal, Hard rock",
  formedYear: 1968,
  cost: 850000,
  img: "https://i.ibb.co/TWZp0jR/deep-purrle.jpg",
 },
 {
  name: "Parkway Drive",
  origin: "Australia",
  genre: "Metalcore",
  formedYear: 2003,
  cost: 350000,
  img: "https://i.ibb.co/DD48W7m/parkwa-drive.jpg",
 },
 {
  name: "Architects",
  origin: "United Kingdom",
  genre: "Metalcore",
  formedYear: 2004,
  cost: 260000,
  img: "https://i.ibb.co/tD8fSjH/architects.jpg",
 },
 {
  name: "Metallica",
  origin: "U.S",
  genre: "Heavy metal",
  formedYear: 2004,
  cost: 780000,
  img: "https://i.ibb.co/QJsKRs7/metallica.jpg",
 },
 {
  name: "Coldplay",
  origin: "England",
  genre: "Rock",
  formedYear: 1996,
  cost: 620000,
  img: "https://i.ibb.co/Fsp0qXD/LOS-ANGELES-CA-NOVEMBER-22-L-R-Recording-artists-Jonny-Buckland-Chris-Martin-Will-Champion-and-Guy-B.jpg",
 },
 {
  name: "Dream Theater",
  origin: "U.S",
  genre: "Progressive metal",
  formedYear: 1985,
  cost: 880000,
  img: "https://i.ibb.co/6PtMRNF/dream-theater.jpg",
 },
 {
  name: "Slipknot",
  origin: "Heavy metal",
  genre: "Progressive metal",
  formedYear: 1995,
  cost: 630000,
  img: "https://i.ibb.co/J3zk0f0/Slipknot.jpg",
 },
 {
  name: "Eluveitie",
  origin: "Switzerland",
  genre: "Folk metal",
  formedYear: 2002,
  cost: 870000,
  img: "https://i.ibb.co/TgDJddB/Eluveitie.jpg",
 },
 {
  name: "Rammstein",
  origin: "Germany",
  genre: "Industrial metal",
  formedYear: 1994,
  cost: 580000,
  img: "https://i.ibb.co/GVKJhCJ/Rammstein.jpg",
 },
];
